id: op:P000781
initial_creation_type: input
source_metadata:
  id:
  source_src: 
  source_brc: 
  source_url: 
  title: ༄༅། །བློ་སྦྱོང་ཚིག་བརྒྱད་མ་བཞུགས་སོ། །
  author: 'དགེ་བཤེས་གླང་རི་ཐང་པ་རྡོ་རྗེ་སེངྒེ།'
